### ISSUE TITLE
Use a generic Interval or Range class.

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/pub_semver#3]
Instead of a custom `VersionRange` class, it would be nice to use a generic `Interval` or `Range` class.  I have a version of `Interval` [here](https://github.com/google/quiver-dart/pull/114) that I'd like to publish as an `interval` package that could be used.  The repo for this package could be kept under the [the dart-lang github org](https://github.com/dart-lang).

Then `VersionConstraint` could have an `interval` property which returned an `Interval<Version>`.  Then instead of `Version` implementing `VersionConstraint`, could have `new VersionConstraint.exact(version)` whose `interval` could use [Interval.singleton](https://github.com/google/quiver-dart/pull/114/files#diff-6af8f2eacfbc01c407305cc2f37d01dcR185) underneath.  Then any custom `toString()` or `==` would be on `VersionConstraint` subclasses, and not on the interval itself.

This would of course be a breaking change, but there probably aren't too many consumers of this package yet, just a really big one in pub :).

**Comment by nex3** [comment]
I don't think we'd get enough benefit from this to make the migration worth it, nor does it seem like the `interval` package is actively maintained anymore.
