### ISSUE TITLE
Library doesn't account for packages with a non-numeric build version.

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/pub_semver#39]
This package currently throws a `FormatException: Invalid radix-10 number (at character 1)
dart2
^
`
for the string: "3.0.2+dart2"

When the documentation from [semver.org](https://semver.org/#spec-item-10
) gives a similar string in the examples. 
> Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

**Comment by munificent** [comment]
I'm unable to repro this. Are you sure that's the exact string to passed to it? Can you show the entire stack trace?

**Comment by ThinkDigitalSoftware** [comment]
The string is taken from this [pub page](https://pub.dev/packages/over_react/versions)

**Comment by ThinkDigitalSoftware** [comment]
You're right, it's no longer throwing. My mistake. I'll reopen if I encounter this again.

**Comment by ThinkDigitalSoftware** [comment]
for some reason, it doesn't print a stacktrace. Another odd thing is that I can't reproduce this in the library I'm using that calls this function, but it does happen in my flutter app. 
<img width="1282" alt="Screen Shot 2019-11-14 at 4 25 21 PM" src="https://user-images.githubusercontent.com/23037821/68907126-85d35900-06fb-11ea-9c5f-949f0814b36f.png">
You can see in the screenshot that an error is being thrown by what's at the top of the stack. I've hovered over the value being parsed. This doesn't cause any issues in my application, but it does throw when I have it breaking on all exceptions.

**Comment by ThinkDigitalSoftware** [comment]
If you want to try it yourself, the source is [here](https://github.com/ThinkDigitalSoftware/tavern) and all you have to do is search for and open [over_react](https://pub.dev/packages/over_react)

**Comment by munificent** [comment]
Those line numbers don't line up with the current source. Are you possibly using an older version of pub_semver?

**Comment by ThinkDigitalSoftware** [comment]
Which line exactly? I don't see any line numbers in the screenshot visible for the semver package

**Comment by ThinkDigitalSoftware** [comment]
But yes, I'm using v1.4.2

**Comment by munificent** [comment]
> Which line exactly? I don't see any line numbers in the screenshot visible for the semver package

`Version._splitParts() (version.dart:160)`

> But yes, I'm using v1.4.2

Might want to upgrade then. It seems to be fixed in the latest version. :)

**Comment by ThinkDigitalSoftware** [comment]
> > Which line exactly? I don't see any line numbers in the screenshot visible for the semver package
> 
> `Version._splitParts() (version.dart:160)`
> 
> > But yes, I'm using v1.4.2
> 
> Might want to upgrade then. It seems to be fixed in the latest version. :)

according to [pub](https://pub.dev/packages/pub_semver), that **is** the latest version

**Comment by ThinkDigitalSoftware** [comment]
I see there's a 1.4.3-dev on github. I'll check with that one.

**Comment by ThinkDigitalSoftware** [comment]
OK. I figured out what it is. It's because I have pause on all exceptions enabled in one project and not in the other. 
Solution: 
Instead of catching parsing errors with `int.parse` how about using `int.tryParse` and if it's null, then return the part.
Original:
https://github.com/dart-lang/pub_semver/blob/b648a2f3700f77c7d3506bad4839885e53d0715c/lib/src/version.dart#L149-L158

Proposed:
```dart
 static List _splitParts(String text) { 
   return text.split('.').map((part) { 
       return int.tryParse(part) ?? part; 
     } 
   }).toList(); 
 } 
```

**Comment by sigurdm** [comment]
This seems stale.
