### ISSUE TITLE
Version.primary - document that this may return null

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub_semver#6]

**Comment by nex3** [comment]
I personally think it's clear that if you pass an empty list to a method that selects something from a list, it'll return `null` unless otherwise documented.

**Comment by kevmoo** [comment]
But it also may return null, even for a non-empty list. That's the crux for me.

**Comment by nex3** [comment]
Looking at the code, I don't see how.

**Comment by kevmoo** [comment]
Hmm...perhaps not. Sorry.

**Comment by nex3** [comment]
Can I close this then?

**Comment by kevmoo** [comment]
Yup.

On Mon, Mar 9, 2015 at 2:43 PM, Natalie Weizenbaum <notifications@github.com
